### ISSUE TITLE
About and documentation refers to not available kelvin13.github.io/jpeg/

### ISSUE THREAD

**Issue by valeriyvan** [kelvin13/jpeg#19]

**Comment by Troll321** [comment]
I don't know if this would help, but the domain change from:
kelvin13.github.io --> [tayloraswift.github.io](https://tayloraswift.github.io/jpeg/)

**Comment by valeriyvan** [comment]
> I don't know if this would help, but the domain change from: kelvin13.github.io --> [tayloraswift.github.io](https://tayloraswift.github.io/jpeg/)

Yes, but all links there are broken as well.
I thought author might be interested for a fix therefore I opened an issue.

**Comment by tayloraswift** [comment]
this isn’t a great answer, but your best source will probably be the Swiftinit-generated symbol documentation here: https://swiftinit.org/docs/tayloraswift.jpeg 

the reason i do not link to it from the repo is that the docs don’t render correctly in DocC, as they were written with a older, non-DocC syntax that is no longer supported. so the Swiftinit docs have a lot of [weird rendering errors](https://swiftinit.org/docs/tayloraswift.jpeg/jpeg/jpeg).

we really should migrate the project to DocC, as this is clearly not a great situation. i just haven’t had time to get around to that yet.

**Comment by tayloraswift** [comment]
docs have been migrated in #25 and are now available at https://swiftinit.org/docs/swift-jpeg
