### ISSUE TITLE
Impossible to use both swift-png and jpeg packages as dependencies in same package

### ISSUE THREAD

**Issue by valeriyvan** [kelvin13/jpeg#4]
Does this look like impossibility to use both swift-png and jpeg packages in same package as dependencies?

```
error project: multiple products named 'unit-test' in: 'jpeg', 'swift-png'
error project: multiple products named 'in-memory' in: 'jpeg', 'swift-png'
error project: multiple products named 'integration-test' in: 'jpeg', 'swift-png'
error project: multiple products named 'decode-basic' in: 'jpeg', 'swift-png'
error project: multiple products named 'custom-color' in: 'jpeg', 'swift-png'
error project: multiple products named 'encode-basic' in: 'jpeg', 'swift-png'
error project: multiple products named 'decode-online' in: 'jpeg', 'swift-png'
```

**Comment by valeriyvan** [comment]
Asked a question in Swift forums https://forums.swift.org/t/product-names-from-different-packages-collide-if-packages-are-used-as-dependencies-in-same-package/60178

**Comment by tayloraswift** [comment]
wow great catch! running the pipeline for your PR rn

**Comment by valeriyvan** [comment]
Both `swift-png` and `jpeg` packages could be used together if module aliasing is used for one of packages like in this [PR](https://github.com/valeriyvan/swift-geometrize/pull/116/files).
